version: "3.8"

services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"   # poprawione
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  react-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
